name: Cloning


on: [push] 

env:
  GIT_URL: https://github.com/Kirin420/GetProCommitNumber

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone your code
         run: | 
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install git expect
              git config --global user.name "Kirin420"
              git config --global user.email "secrets.EMAIL"
              mkdir bruh &&cd bruh
              git clone $GIT_URL bruh
              
       - name: You're a retard
         continue-on-error: true
         timeout-minutes: 2
         run: |
              echo "69" >> var.txt
              
       - name: commit
         continue-on-error: true
         run: |
              cd bruh/bruh
              git add var.txt
              git commit -m "Add a variable"
       
       - name: commit it finally
         run: |
             cd bruh/bruh
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"Kirin420\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
         
